//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catriges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catriges()
        {
            this.Replacement = new HashSet<Replacement>();
            this.Seizure = new HashSet<Seizure>();
        }
    
        public int CatrigesID { get; set; }
        public string SerialNuber { get; set; }
        public Nullable<int> PrinterModelID { get; set; }
        public Nullable<int> ColorModelID { get; set; }
        public Nullable<int> CatrigeStatusID { get; set; }
    
        public virtual CatrigeStatus CatrigeStatus { get; set; }
        public virtual ModelPrinter ModelPrinter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Replacement> Replacement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seizure> Seizure { get; set; }
    }
}
