//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationPrinter
    {
        public int LocationPrinterID { get; set; }
        public int TitulNumber { get; set; }
        public Nullable<int> Cabinet { get; set; }
        public string Discription { get; set; }
        public int PrinterID { get; set; }
    
        public virtual Printers Printers { get; set; }
    }
}
