//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelColors
    {
        public int ModelColorID { get; set; }
        public string ModelColorName { get; set; }
        public Nullable<int> ColorID { get; set; }
    
        public virtual Color Color { get; set; }
    }
}
