//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Printers()
        {
            this.LocationPrinter = new HashSet<LocationPrinter>();
        }
    
        public int PrinterID { get; set; }
        public string SerialNamber { get; set; }
        public Nullable<int> ModelPrinterID { get; set; }
        public Nullable<int> PrinterStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationPrinter> LocationPrinter { get; set; }
        public virtual ModelPrinter ModelPrinter { get; set; }
        public virtual PrinterStatus PrinterStatus { get; set; }
    }
}
